# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_auto_20150515_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderatedobject',
            options={'ordering': ['moderation_status', 'date_created'], 'verbose_name': 'Moderated Object', 'verbose_name_plural': 'Moderated Objects'},
        ),
    ]
